/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-us-page': AboutUsPage;
    'loan-page': LoanPage;
    'how-to-apply-page': HowToApplyPage;
    'contact-us-page': ContactUsPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-us-page': AboutUsPageSelect<false> | AboutUsPageSelect<true>;
    'loan-page': LoanPageSelect<false> | LoanPageSelect<true>;
    'how-to-apply-page': HowToApplyPageSelect<false> | HowToApplyPageSelect<true>;
    'contact-us-page': ContactUsPageSelect<false> | ContactUsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  internalName?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  internalName?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  header: {
    websiteLogo?: (number | null) | Media;
    mobileDrawerLogo?: (number | null) | Media;
    aboutUsMenuLabel: string;
    loanMenuLabel: string;
    howToApplyMenuLabel: string;
    contactUsMenuLabel: string;
    applyNowButtonLabel: string;
    loginButtonLabel: string;
    newsletterLabel: string;
  };
  footer: {
    footerLogo?: (number | null) | Media;
    pagesColumnHeading: string;
    homeLinkLabel: string;
    aboutUsLinkLabel: string;
    loanLinkLabel: string;
    helpColumnHeading: string;
    howToApplyLinkLabel: string;
    contactUsLinkLabel: string;
    copyrightText: string;
  };
  contactDetails: {
    supportEmail: string;
    displayPhoneNumber: string;
    officeName: string;
    officeAddress: string;
    wazeUrl?: string | null;
    googleMapsUrl?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  seo: {
    title: string;
    description?: string | null;
  };
  hero: {
    eyebrow: string;
    mainHeading: string;
    description: string;
    primaryButtonLabel: string;
    secondaryButtonLabel: string;
    leftTopImage?: (number | null) | Media;
    rightTopImage?: (number | null) | Media;
    bottomLeftImage?: (number | null) | Media;
    bottomRightImage?: (number | null) | Media;
  };
  howItWorks: {
    heading: string;
    description: string;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  statistics?: {
    items?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  loanOptions: {
    heading: string;
    description: string;
    cards?:
      | {
          image?: (number | null) | Media;
          title: string;
          description: string;
          linkLabel: string;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs: {
    image?: (number | null) | Media;
    heading: string;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  readyToGetStarted: {
    heading: string;
    description: string;
    applyButtonLabel: string;
    whatsappButtonLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page".
 */
export interface AboutUsPage {
  id: number;
  seo: {
    title: string;
    description?: string | null;
  };
  hero: {
    backgroundImage?: (number | null) | Media;
    mainHeading: string;
    description: string;
  };
  whoWeAre: {
    image?: (number | null) | Media;
    heading: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    statistics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  whyChooseUs: {
    heading: string;
    description: string;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  trustAndSecurity: {
    heading: string;
    description: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
  };
  whoWeHelp: {
    heading: string;
    description: string;
    cards?:
      | {
          image?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  readyToGetStarted: {
    heading: string;
    description: string;
    applyButtonLabel: string;
    advisorButtonLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-page".
 */
export interface LoanPage {
  id: number;
  seo: {
    title: string;
    description?: string | null;
  };
  hero: {
    mainHeading: string;
    description: string;
    primaryButtonLabel: string;
    secondaryButtonLabel: string;
    image?: (number | null) | Media;
  };
  personalLoan: {
    heading: string;
    description: string;
    applyButtonLabel: string;
    whatsappButtonLabel: string;
    features?:
      | {
          image?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    requirements: {
      image?: (number | null) | Media;
      heading: string;
      items?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  businessLoan: {
    heading: string;
    description: string;
    applyButtonLabel: string;
    whatsappButtonLabel: string;
    features?:
      | {
          image?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    requirements: {
      image?: (number | null) | Media;
      heading: string;
      items?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  comparison: {
    heading: string;
    description: string;
    tableHeading: string;
    personalColumn: {
      title: string;
      subtitle: string;
    };
    businessColumn: {
      title: string;
      subtitle: string;
    };
    rows?:
      | {
          label: string;
          personalValue: string;
          businessValue: string;
          id?: string | null;
        }[]
      | null;
    loanDetailsHeading: string;
    applicationNeedsHeading: string;
  };
  interestRates: {
    heading: string;
    description: string;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  estimator: {
    heading: string;
    disclaimer: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-to-apply-page".
 */
export interface HowToApplyPage {
  id: number;
  seo: {
    title: string;
    description?: string | null;
  };
  hero: {
    mainHeading: string;
    description: string;
    primaryButtonLabel: string;
  };
  steps: {
    heading: string;
    description: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  requiredDocuments: {
    image?: (number | null) | Media;
    heading: string;
    description: string;
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  eligibility: {
    heading: string;
    description: string;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  readyToApply: {
    heading: string;
    description: string;
    whatsappButtonLabel: string;
    submitButtonLabel: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page".
 */
export interface ContactUsPage {
  id: number;
  seo: {
    title: string;
    description?: string | null;
  };
  contactForm: {
    heading: string;
    description: string;
    submitButtonLabel: string;
    image?: (number | null) | Media;
  };
  contactMethods: {
    email: {
      heading: string;
      description: string;
    };
    phone: {
      heading: string;
    };
    office: {
      heading: string;
      description: string;
    };
  };
  faq: {
    heading: string;
    description: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  stillHaveQuestions: {
    heading: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  header?:
    | T
    | {
        websiteLogo?: T;
        mobileDrawerLogo?: T;
        aboutUsMenuLabel?: T;
        loanMenuLabel?: T;
        howToApplyMenuLabel?: T;
        contactUsMenuLabel?: T;
        applyNowButtonLabel?: T;
        loginButtonLabel?: T;
        newsletterLabel?: T;
      };
  footer?:
    | T
    | {
        footerLogo?: T;
        pagesColumnHeading?: T;
        homeLinkLabel?: T;
        aboutUsLinkLabel?: T;
        loanLinkLabel?: T;
        helpColumnHeading?: T;
        howToApplyLinkLabel?: T;
        contactUsLinkLabel?: T;
        copyrightText?: T;
      };
  contactDetails?:
    | T
    | {
        supportEmail?: T;
        displayPhoneNumber?: T;
        officeName?: T;
        officeAddress?: T;
        wazeUrl?: T;
        googleMapsUrl?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        mainHeading?: T;
        description?: T;
        primaryButtonLabel?: T;
        secondaryButtonLabel?: T;
        leftTopImage?: T;
        rightTopImage?: T;
        bottomLeftImage?: T;
        bottomRightImage?: T;
      };
  howItWorks?:
    | T
    | {
        heading?: T;
        description?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  statistics?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  loanOptions?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              linkLabel?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        image?: T;
        heading?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  readyToGetStarted?:
    | T
    | {
        heading?: T;
        description?: T;
        applyButtonLabel?: T;
        whatsappButtonLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-page_select".
 */
export interface AboutUsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        backgroundImage?: T;
        mainHeading?: T;
        description?: T;
      };
  whoWeAre?:
    | T
    | {
        image?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        statistics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  whyChooseUs?:
    | T
    | {
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  trustAndSecurity?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        image?: T;
      };
  whoWeHelp?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  readyToGetStarted?:
    | T
    | {
        heading?: T;
        description?: T;
        applyButtonLabel?: T;
        advisorButtonLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loan-page_select".
 */
export interface LoanPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        mainHeading?: T;
        description?: T;
        primaryButtonLabel?: T;
        secondaryButtonLabel?: T;
        image?: T;
      };
  personalLoan?:
    | T
    | {
        heading?: T;
        description?: T;
        applyButtonLabel?: T;
        whatsappButtonLabel?: T;
        features?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              image?: T;
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  businessLoan?:
    | T
    | {
        heading?: T;
        description?: T;
        applyButtonLabel?: T;
        whatsappButtonLabel?: T;
        features?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              image?: T;
              heading?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  comparison?:
    | T
    | {
        heading?: T;
        description?: T;
        tableHeading?: T;
        personalColumn?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        businessColumn?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        rows?:
          | T
          | {
              label?: T;
              personalValue?: T;
              businessValue?: T;
              id?: T;
            };
        loanDetailsHeading?: T;
        applicationNeedsHeading?: T;
      };
  interestRates?:
    | T
    | {
        heading?: T;
        description?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  estimator?:
    | T
    | {
        heading?: T;
        disclaimer?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-to-apply-page_select".
 */
export interface HowToApplyPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        mainHeading?: T;
        description?: T;
        primaryButtonLabel?: T;
      };
  steps?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  requiredDocuments?:
    | T
    | {
        image?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  eligibility?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  readyToApply?:
    | T
    | {
        heading?: T;
        description?: T;
        whatsappButtonLabel?: T;
        submitButtonLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-us-page_select".
 */
export interface ContactUsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  contactForm?:
    | T
    | {
        heading?: T;
        description?: T;
        submitButtonLabel?: T;
        image?: T;
      };
  contactMethods?:
    | T
    | {
        email?:
          | T
          | {
              heading?: T;
              description?: T;
            };
        phone?:
          | T
          | {
              heading?: T;
            };
        office?:
          | T
          | {
              heading?: T;
              description?: T;
            };
      };
  faq?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  stillHaveQuestions?:
    | T
    | {
        heading?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}